version: '3'
services:
  NetCore:
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/app/
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    entrypoint: sh -c "cd /app && dotnet ${PANEL_APP_NAME}"
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true